#ifndef GINS_RESOURCE_H
#define GINS_RESOURCE_H

//{{NO_DEPENDENCIES}}
#define IDI_ICON 102

#define IDI_ICON_SMALL 105

#define IDI_ICON_LARGE 108

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 105
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif

#endif